screens:
  - name: "Default"
    colormode: RGB24 #rgb24|rgb16|grey8|binary
    width: 128
    height: 64
    background: "000000" #rgb color (hex)
    showgrid: true #show grid [true|false]
    gridsize: 2 #grid size [number]
    scale: 4 #pixels per pixel [number]
    refresh: 16 #ms
  - name: "tinyled16x16"
    colormode: RGB24 #rgb24|rgb16|grey8|binary
    width: 16
    height: 16
    background: "000000" #rgb color (hex)
    showgrid: true #show grid [true|false]
    gridsize: 2 #grid size [number]
    scale: 10 #pixels per pixel [number]
    refresh: 16 #ms
fonts:
  - name: "5x5"
    file: "data/fonts/5x5_pixel.ttf"
    glyphs: ' !"%()+=,-.:/0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz°'
    size: 8
  - name: "8Bit HUD"
    file: "data/fonts/8-bit-hud.ttf"
    glyphs: ' !"%()+=,-.:/0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz°'
    size: 5

  - name: "squares"
    file: "data/fonts/Squares.ttf"
    glyphs: ' !"%()+=,-.:/0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz°'
    size: 4

animations:
  - include: "data/animations/*.[gG][iI][fF]"

images:
  - include: "data/images/18x18_emojis/*.png"
  - include: "data/images/16x16_bw_icons/*.png"
  - include: "data/images/16x16_color_icons/*.png"
  - include: "data/images/*.[pP][nN][gG]"
